<html>
 <head>
 </head>
 <body>
  <pre>
    <a name="line_1"></a># Let K be the field of rational functions on EX^*, and let KT be the biquadratic
<a name="line_2"></a># extension generated by r[1] = sqrt(1 - y[2]/sqrt(2)) and r[2] = sqrt(1 + y[2]/sqrt(2)).
<a name="line_3"></a># This file defines many elements of KT and relations between them, which are
<a name="line_4"></a># useful for studying the Galois theory of various intermediate fields.
<a name="line_5"></a># The relevant Galois group is defined in the file group64.mpl
<a name="line_6"></a>
<a name="line_7"></a># These elements t[i] are used when studying torus quotients of EX^*
<a name="line_8"></a>
<a name="line_9"></a><span style="color:red">#@ tx
</span><a name="line_10"></a>tx[1] := (r[1]+1/sqrt(2))*(1-r[1]*y[1])/x[1];
<a name="line_11"></a>tx[2] := (r[2]+1/sqrt(2))*(1-r[2]*y[1])/x[2];
<a name="line_12"></a>tx[3] := (r[1]+1/sqrt(2))*(1+r[1]*y[1])/x[1];
<a name="line_13"></a>tx[4] := (r[2]+1/sqrt(2))*(1+r[2]*y[1])/x[2];
<a name="line_14"></a>
<a name="line_15"></a># These are expressions for t[i] in terms of y[1], r[1] and r[2].
<a name="line_16"></a># They are correct on F16 but have the wrong sign in some other places.
<a name="line_17"></a><span style="color:red">#@ tr
</span><a name="line_18"></a>tr[1] := sqrt((r[1]+1/sqrt(2))*(1-r[1]*y[1])/((r[1]-1/sqrt(2))*(1+r[1]*y[1])));
<a name="line_19"></a>tr[2] := sqrt((r[2]+1/sqrt(2))*(1-r[2]*y[1])/((r[2]-1/sqrt(2))*(1+r[2]*y[1])));
<a name="line_20"></a>tr[3] := sqrt((r[1]+1/sqrt(2))*(1+r[1]*y[1])/((r[1]-1/sqrt(2))*(1-r[1]*y[1])));
<a name="line_21"></a>tr[4] := sqrt((r[2]+1/sqrt(2))*(1+r[2]*y[1])/((r[2]-1/sqrt(2))*(1-r[2]*y[1])));
<a name="line_22"></a>
<a name="line_23"></a># Some further elements with nice transformation properties
<a name="line_24"></a><span style="color:red">#@ st
</span><a name="line_25"></a>st[ 1] := t[3]*t[1]:
<a name="line_26"></a>st[ 2] := t[4]*t[2]:
<a name="line_27"></a>st[ 3] := t[3]/t[1]:
<a name="line_28"></a>st[ 4] := t[4]/t[2]:
<a name="line_29"></a>st[ 5] := st[1]/2+1/st[1]/2-2:
<a name="line_30"></a>st[ 6] := st[2]/2+1/st[2]/2-2:
<a name="line_31"></a>st[ 7] := st[3]/2+1/st[3]/2:
<a name="line_32"></a>st[ 8] := st[4]/2+1/st[4]/2:
<a name="line_33"></a>st[ 9] := (t[1]+1/t[1])/2:
<a name="line_34"></a>st[10] := (t[2]+1/t[2])/2:
<a name="line_35"></a>st[11] := (t[3]+1/t[3])/2:
<a name="line_36"></a>st[12] := (t[4]+1/t[4])/2:
<a name="line_37"></a>st[13] := t[1]*t[2] - t[3]*t[4]:
<a name="line_38"></a>st[14] := t[1]/t[2] - t[3]/t[4]:
<a name="line_39"></a>st[15] := t[2]/t[1] - t[4]/t[3]:
<a name="line_40"></a>st[16] := 1/(t[1]*t[2]) - 1/(t[3]*t[4]):
<a name="line_41"></a>
<a name="line_42"></a># Expressions for s[i] in terms of y[1], y[2], r[1], r[2]
<a name="line_43"></a><span style="color:red">#@ sx
</span><a name="line_44"></a>sx[ 1] := (r[1] + 1/sqrt(2))/(r[1] - 1/sqrt(2));
<a name="line_45"></a>sx[ 2] := (r[2] + 1/sqrt(2))/(r[2] - 1/sqrt(2));
<a name="line_46"></a>sx[ 3] := (1 + r[1]*y[1])/(1 - r[1]*y[1]);
<a name="line_47"></a>sx[ 4] := (1 + r[2]*y[1])/(1 - r[2]*y[1]);
<a name="line_48"></a>sx[ 5] := (1 + y[2]*sqrt(2))/(1 - y[2]*sqrt(2));
<a name="line_49"></a>sx[ 6] := (1 - y[2]*sqrt(2))/(1 + y[2]*sqrt(2));
<a name="line_50"></a>sx[ 7] := (1 + y[1]^2*(1 - y[2]/sqrt(2)))/(1 - y[1]^2*(1 - y[2]/sqrt(2)));
<a name="line_51"></a>sx[ 8] := (1 + y[1]^2*(1 + y[2]/sqrt(2)))/(1 - y[1]^2*(1 + y[2]/sqrt(2)));
<a name="line_52"></a>sx[ 9] := 2*r[1]*x[1]*(1-y[1]/sqrt(2))/((1 - y[1]^2*(1-y[2]/sqrt(2)))*(1-y[2]*sqrt(2)));
<a name="line_53"></a>sx[10] := 2*r[2]*x[2]*(1-y[1]/sqrt(2))/((1 - y[1]^2*(1+y[2]/sqrt(2)))*(1+y[2]*sqrt(2)));
<a name="line_54"></a>sx[11] := 2*r[1]*x[1]*(1+y[1]/sqrt(2))/((1 - y[1]^2*(1-y[2]/sqrt(2)))*(1-y[2]*sqrt(2)));
<a name="line_55"></a>sx[12] := 2*r[2]*x[2]*(1+y[1]/sqrt(2))/((1 - y[1]^2*(1+y[2]/sqrt(2)))*(1+y[2]*sqrt(2)));
<a name="line_56"></a>sx[13] := -2*y[1]*(r[1]+1/sqrt(2))*(r[2]+1/sqrt(2))*(r[1]+r[2])/(x[1]*x[2]);
<a name="line_57"></a>sx[14] := -2*y[1]*(r[1]+1/sqrt(2))*(r[2]-1/sqrt(2))*(r[1]-r[2])/(x[1]*x[2]);
<a name="line_58"></a>sx[15] :=  2*y[1]*(r[1]-1/sqrt(2))*(r[2]+1/sqrt(2))*(r[1]-r[2])/(x[1]*x[2]);
<a name="line_59"></a>sx[16] :=  2*y[1]*(r[1]-1/sqrt(2))*(r[2]-1/sqrt(2))*(r[1]+r[2])/(x[1]*x[2]);
<a name="line_60"></a>
<a name="line_61"></a># Another family of elements with nice transformation properties
<a name="line_62"></a><span style="color:red">#@ ut
</span><a name="line_63"></a>ut[ 1] := t[1]+t[3]:
<a name="line_64"></a>ut[ 5] := t[1]-t[3]:
<a name="line_65"></a>ut[ 9] := t[1]-1/t[3]:
<a name="line_66"></a>ut[13] := t[1]+1/t[3]:
<a name="line_67"></a>for i from 0 to 3 do
<a name="line_68"></a> ut[4*i+2] := act_AT[L](ut[4*i+1]);
<a name="line_69"></a> ut[4*i+3] := act_AT[A1](ut[4*i+1]);
<a name="line_70"></a> ut[4*i+4] := act_AT[LA1](ut[4*i+1]);
<a name="line_71"></a>od:
<a name="line_72"></a>
<a name="line_73"></a>for i from 1 to 16 do
<a name="line_74"></a> ux[i] := FNF_y0(eval(subs(t = tx,ut[i])));
<a name="line_75"></a>od:
<a name="line_76"></a>
<a name="line_77"></a><span style="color:red">#@ tu
</span><a name="line_78"></a>tu[ 1] := u[1]/2 + u[5]/2;
<a name="line_79"></a>tu[ 2] := u[2]/2 + u[6]/2;
<a name="line_80"></a>tu[ 3] := u[1]/2 - u[5]/2;
<a name="line_81"></a>tu[ 4] := u[2]/2 - u[6]/2;
<a name="line_82"></a>
<a name="line_83"></a><span style="color:red">#@ su
</span><a name="line_84"></a>su[ 1] := - u[ 1]/u[ 3];
<a name="line_85"></a>su[ 2] := - u[ 2]/u[ 4];
<a name="line_86"></a>su[ 3] := - u[15]/u[13];
<a name="line_87"></a>su[ 4] := - u[16]/u[14];
<a name="line_88"></a>su[ 5] :=   u[ 9]*u[11]/2 - 1;
<a name="line_89"></a>su[ 6] :=   u[10]*u[12]/2 - 1;
<a name="line_90"></a>su[ 7] := - u[ 1]*u[ 3]/2 - 1;
<a name="line_91"></a>su[ 8] := - u[ 2]*u[ 4]/2 - 1;
<a name="line_92"></a>su[ 9] :=   ( u[ 1] - u[11])/2;
<a name="line_93"></a>su[10] :=   ( u[ 2] - u[12])/2;
<a name="line_94"></a>su[11] :=   (-u[ 3] + u[11])/2;
<a name="line_95"></a>su[12] :=   (-u[ 4] + u[12])/2;
<a name="line_96"></a>su[13] :=   (u[ 1]*u[ 6]+u[ 2]*u[ 5])/2;
<a name="line_97"></a>su[14] := - (u[ 4]*u[ 5]+u[ 1]*u[ 8])/2;
<a name="line_98"></a>su[15] := - (u[ 3]*u[ 6]+u[ 2]*u[ 7])/2;
<a name="line_99"></a>su[16] :=   (u[ 3]*u[ 8]+u[ 4]*u[ 7])/2;
<a name="line_100"></a>
<a name="line_101"></a><span style="color:red">#@ au
</span><a name="line_102"></a>au[1] := factor(1/(1/u[1]+1/u[3]));
<a name="line_103"></a>au[2] := factor(1/(1/u[6]+1/u[8]));
<a name="line_104"></a>
<a name="line_105"></a><span style="color:red">#@ bu
</span><a name="line_106"></a>bu[1] := u[1]*u[3];
<a name="line_107"></a>bu[2] := u[6]*u[8];
<a name="line_108"></a>
<a name="line_109"></a><span style="color:red">#@ bs
</span><a name="line_110"></a>bs[1] := -2*(s[7]+1);
<a name="line_111"></a>bs[2] :=  2*(s[8]-1);
<a name="line_112"></a>
<a name="line_113"></a># Expressions for x[i], y[i], z[i], r[i] in terms of s[j]
<a name="line_114"></a>zs[1]     := (s[7]*s[8]-1)/((1+s[7])*(1+s[8]));            <span style="color:red">#@ zs
</span><a name="line_115"></a>ys[1]     := sqrt(2)*(s[3]-1)/(s[3]+1)*(s[1]-1)/(s[1]+1);  <span style="color:red">#@ ys
</span><a name="line_116"></a>ys_alt[1] := sqrt(2)*(s[4]-1)/(s[4]+1)*(s[2]-1)/(s[2]+1);  <span style="color:red">#@ ys_alt
</span><a name="line_117"></a>ys[2]     := sqrt(2)*(s[8]-s[7])/(s[7]*s[8]-1);
<a name="line_118"></a>xs[1] := 2*sqrt(2)*t[3]/((s[1]-1)*(s[3]+1));               <span style="color:red">#@ xs
</span><a name="line_119"></a>xs[2] := 2*sqrt(2)*t[4]/((s[2]-1)*(s[4]+1));
<a name="line_120"></a>xs[3] := ys[1];
<a name="line_121"></a>xs[4] := -ys[1]*ys[2];
<a name="line_122"></a>rs[1] := (s[1]+1)/(s[1]-1)/sqrt(2);                        <span style="color:red">#@ rs
</span><a name="line_123"></a>rs[2] := (s[2]+1)/(s[2]-1)/sqrt(2);
<a name="line_124"></a>
<a name="line_125"></a># Expressions for x[i], y[i], z[i], r[i] in terms of t[j]
<a name="line_126"></a>zt[1]     := eval(subs(s = st,zs[1]    )):                 <span style="color:red">#@ zt
</span><a name="line_127"></a>yt[1]     := eval(subs(s = st,ys[1]    )):                 <span style="color:red">#@ yt
</span><a name="line_128"></a>yt_alt[1] := eval(subs(s = st,ys_alt[1])):                 <span style="color:red">#@ yt_alt
</span><a name="line_129"></a>yt[2]     := eval(subs(s = st,ys[2]    )):
<a name="line_130"></a>xt[1]     := eval(subs(s = st,xs[1]    )):                 <span style="color:red">#@ xt
</span><a name="line_131"></a>xt[2]     := eval(subs(s = st,xs[2]    )):
<a name="line_132"></a>xt[3]     := eval(subs(s = st,xs[3]    )):
<a name="line_133"></a>xt[4]     := eval(subs(s = st,xs[4]    )):
<a name="line_134"></a>rt[1]     := eval(subs(s = st,rs[1]    )):                 <span style="color:red">#@ rt
</span><a name="line_135"></a>rt[2]     := eval(subs(s = st,rs[2]    )):
<a name="line_136"></a>
<a name="line_137"></a># Relations among the elements t[i]
<a name="line_138"></a><span style="color:red">#@ t_rels
</span><a name="line_139"></a>t_rels[ 1] := t[1]^2*t[2]^2*t[3]^2*t[4]^2-4*t[1]^2*t[2]*t[3]^2*t[4]-4*t[1]*t[2]^2*t[3]*t[4]^2+t[1]^2*t[3]^2+12*t[1]*t[2]*t[3]*t[4]+t[2]^2*t[4]^2-4*t[1]*t[3]-4*t[2]*t[4]+1;
<a name="line_140"></a>t_rels[ 2] := t[1]^2*t[2]*t[3]*t[4]^2-t[1]*t[2]^2*t[3]^2*t[4]+t[1]^2*t[2]*t[3]-t[1]*t[2]^2*t[4]-t[1]*t[3]^2*t[4]+t[2]*t[3]*t[4]^2-t[1]*t[4]+t[2]*t[3];
<a name="line_141"></a>
<a name="line_142"></a><span style="color:red">#@ ts_rels
</span><a name="line_143"></a>ts_rels[1] := tan_sum(t[1], t[3]) + ((t[1]+t[3])*(r[1]-1/sqrt(2))/sqrt(2));
<a name="line_144"></a>ts_rels[2] := tan_sum(t[2], t[4]) + ((t[2]+t[4])*(r[2]-1/sqrt(2))/sqrt(2));
<a name="line_145"></a>ts_rels[3] := tan_sum(t[1],-t[3]) - ((t[1]-t[3])*(r[1]-1/sqrt(2))/r[1]/2);
<a name="line_146"></a>ts_rels[4] := tan_sum(t[2],-t[4]) - ((t[2]-t[4])*(r[2]-1/sqrt(2))/r[2]/2);
<a name="line_147"></a>
<a name="line_148"></a># Relations among the elements s[i]
<a name="line_149"></a><span style="color:red">#@ s_rels
</span><a name="line_150"></a>s_rels[ 1] := s[5]*s[6]-1;
<a name="line_151"></a>s_rels[ 2] := s[5]*((s[7]-2)*(s[8]+2)+3) - ((s[7]+2)*(s[8]-2)+3);
<a name="line_152"></a>s_rels[ 3] := s[6]*((s[7]+2)*(s[8]-2)+3) - ((s[7]-2)*(s[8]+2)+3);
<a name="line_153"></a>s_rels[ 4] := s[9]/s[11]-s[10]/s[12];
<a name="line_154"></a>s_rels[ 5] := s[1]*s[2]*s[3]-s[1]*s[2]*s[4]+s[1]*s[3]*s[4]-s[2]*s[3]*s[4]-s[1]+s[2]-s[3]+s[4];
<a name="line_155"></a>s_rels[ 6] := s[1]^2*s[2]^2-4*s[1]^2*s[2]-4*s[1]*s[2]^2+s[1]^2+12*s[1]*s[2]+s[2]^2-4*s[1]-4*s[2]+1;
<a name="line_156"></a>s_rels[ 7] := s[13]*s[14]*s[15] + s[13]*s[14]*s[16] + s[13]*s[15]*s[16] + s[14]*s[15]*s[16];
<a name="line_157"></a>s_rels[ 8] := (s[13]-s[14]-s[15]+s[16])^2 + 8*(s[13]+s[14]+s[15]+s[16])^2 - 8*(s[13]-s[16])^2 - 8*(s[14]-s[15])^2;
<a name="line_158"></a>s_rels[ 9] := ((1-4*s[1]+s[1]^2)*(s[2]-2) - 2*s[1])^2 - (1 - s[1])^2*(3*s[1]-1)*(s[1]-3);
<a name="line_159"></a>s_rels[10] := ((1-4*s[2]+s[2]^2)*(s[1]-2) - 2*s[2])^2 - (1 - s[2])^2*(3*s[2]-1)*(s[2]-3);
<a name="line_160"></a>s_rels[11] := s[1]*s[2]*s[16] + s[13];
<a name="line_161"></a>s_rels[12] := s[1]*s[15] + s[2]*s[14];
<a name="line_162"></a>
<a name="line_163"></a># Quadratic relations for t[i] over K
<a name="line_164"></a><span style="color:red">#@ qt_rels
</span><a name="line_165"></a>qt_rels[1] := t[1]^2 -2*sqrt(2)*x[1]*(1-sqrt(2)*y[1]*(1-y[2]/sqrt(2)))/((1-y[2]*sqrt(2))*(1-y[1]^2*(1-y[2]/sqrt(2)))) * t[1] - 1;
<a name="line_166"></a>qt_rels[2] := t[2]^2 -2*sqrt(2)*x[2]*(1-sqrt(2)*y[1]*(1+y[2]/sqrt(2)))/((1+y[2]*sqrt(2))*(1-y[1]^2*(1+y[2]/sqrt(2)))) * t[2] - 1;
<a name="line_167"></a>qt_rels[3] := t[3]^2 -2*sqrt(2)*x[1]*(1+sqrt(2)*y[1]*(1-y[2]/sqrt(2)))/((1-y[2]*sqrt(2))*(1-y[1]^2*(1-y[2]/sqrt(2)))) * t[3] - 1;
<a name="line_168"></a>qt_rels[4] := t[4]^2 -2*sqrt(2)*x[2]*(1+sqrt(2)*y[1]*(1+y[2]/sqrt(2)))/((1+y[2]*sqrt(2))*(1-y[1]^2*(1+y[2]/sqrt(2)))) * t[4] - 1;
<a name="line_169"></a>
<a name="line_170"></a># The relations u_lin_rels[i] and u_quad_rels[i] depend only on the expressions 
<a name="line_171"></a># for the u[i] in terms of the t[j], not on the relations among the t[j]
<a name="line_172"></a>
<a name="line_173"></a><span style="color:red">#@ u_lin_rels
</span><a name="line_174"></a>u_lin_rels := {
<a name="line_175"></a>u[ 1] + u[ 3] - u[ 9] - u[11],
<a name="line_176"></a>u[ 1] + u[ 5] - u[ 9] - u[13],
<a name="line_177"></a>u[ 1] + u[ 7] - u[11] - u[13],
<a name="line_178"></a>u[ 2] + u[ 4] - u[10] - u[12],
<a name="line_179"></a>u[ 2] + u[ 6] - u[10] - u[14],
<a name="line_180"></a>u[ 2] + u[ 8] - u[12] - u[14],
<a name="line_181"></a>u[ 3] + u[ 5] - u[ 9] - u[15],
<a name="line_182"></a>u[ 3] + u[ 7] - u[11] - u[15],
<a name="line_183"></a>u[ 4] + u[ 6] - u[10] - u[16],
<a name="line_184"></a>u[ 4] + u[ 8] - u[12] - u[16],
<a name="line_185"></a>u[ 5] + u[ 7] - u[13] - u[15],
<a name="line_186"></a>u[ 6] + u[ 8] - u[14] - u[16]
<a name="line_187"></a>}:
<a name="line_188"></a>
<a name="line_189"></a><span style="color:red">#@ u_quad_rels
</span><a name="line_190"></a>u_quad_rels := {
<a name="line_191"></a> u[ 1]*u[ 3] + u[ 5]*u[ 7] + 4,
<a name="line_192"></a> u[ 2]*u[ 4] + u[ 6]*u[ 8] + 4,
<a name="line_193"></a> u[ 9]*u[11] + u[13]*u[15] + 4,
<a name="line_194"></a> u[10]*u[12] + u[14]*u[16] + 4,
<a name="line_195"></a> u[ 1]*u[ 7] + u[ 3]*u[ 5],
<a name="line_196"></a> u[ 2]*u[ 8] + u[ 4]*u[ 6],
<a name="line_197"></a> u[ 9]*u[15] + u[11]*u[13],
<a name="line_198"></a> u[10]*u[16] + u[12]*u[14]
<a name="line_199"></a>}:
<a name="line_200"></a>
<a name="line_201"></a># These additional relations depend on relations among the t[j].
<a name="line_202"></a><span style="color:red">#@ u_rels
</span><a name="line_203"></a>u_rels[1] := 1/(u[9]*u[11]) + 1/(u[10]*u[12]) - 1/2;
<a name="line_204"></a>u_rels[2] := u[1]*u[4]-u[4]*u[11]+u[11]*u[2]-u[2]*u[3]+u[3]*u[12]-u[12]*u[1];
<a name="line_205"></a>u_rels[3] := (u[9]*u[11]+u[10]*u[12]-8)*(1/2+1/(u[1]*u[3])+1/(u[2]*u[4]))+2*(u[9]*u[11]-u[10]*u[12])*(1/(u[1]*u[3])-1/(u[2]*u[4]));
<a name="line_206"></a>
<a name="line_207"></a><span style="color:red">#@ ab_rels
</span><a name="line_208"></a>ab_rels[1] := expand((b[1]+2*a[1]^2)*(b[2]-6*a[2]^2) + 4*a[1]^2*a[2]^2);
<a name="line_209"></a>ab_rels[2] := 8*a[2]^2*b[1]-b[1]*b[2]+2*b[1]+2*b[2]+8;
<a name="line_210"></a>ab_rels[3] := ((1+a[2]^2)*(3+2*a[1]^2+b[1])-  (1+a[1]^2))^2 - (a[1]^2-3*a[2]^2-2)^2 - 4*a[1]^2*a[2]^2*(1+a[1]^2)*(1+a[2]^2);
<a name="line_211"></a>ab_rels[4] := ((1+a[1]^2)*(1+6*a[2]^2-b[2])-3*(1+a[2]^2))^2 - (a[1]^2-3*a[2]^2-2)^2 - 4*a[1]^2*a[2]^2*(1+a[1]^2)*(1+a[2]^2);
<a name="line_212"></a>ab_rels[5] := (1+a[1]^2)*b[2] + (1+a[2]^2)*b[1] + 4*(1 - a[1]^2*a[2]^2);
<a name="line_213"></a>ab_rels[6] := a[1]^2 + (1/4)*b[1]*(b[1]*b[2]+6*b[1]+6*b[2]+24)/(b[1]*b[2]+2*b[1]+2*b[2]+8);
<a name="line_214"></a>ab_rels[7] := a[2]^2 - (1/8)*(b[1]*b[2]-2*b[1]-2*b[2]-8)/b[1];
<a name="line_215"></a>
<a name="line_216"></a><span style="color:red">#@ extra_galois_rels
</span><a name="line_217"></a>extra_galois_rels := [
<a name="line_218"></a> tan_sum(t[1], t[3]) - 1/(1/u[1] + 1/u[3]),
<a name="line_219"></a> tan_sum(t[2],-t[4]) - 1/(1/u[6] + 1/u[8]),
<a name="line_220"></a> u[6]*u[8] - 2*(s[8]-1),
<a name="line_221"></a> (u[6]-u[8])^2 -  8*(s[8]-1)*(s[7]*s[8]-1)/(s[7]*s[8]-2*s[7]+2*s[8]-1),
<a name="line_222"></a> (u[6]+u[8])^2 - 16*(s[8]-1)^2*(s[7]+1)   /(s[7]*s[8]-2*s[7]+2*s[8]-1)
<a name="line_223"></a>];
<a name="line_224"></a>
<a name="line_225"></a><span style="color:red">#@ s_to_t 
</span><a name="line_226"></a>s_to_t := {seq(s[i]=st[i],i=1..16),seq(u[i]=ut[i],i=1..16)}:
<a name="line_227"></a>
<a name="line_228"></a><span style="color:red">#@ t_to_xyz 
</span><a name="line_229"></a>t_to_xyz := {seq(t[i]=tx[i],i=1..4),seq(s[i]=sx[i],i=1..16),seq(u[i]=ux[i],i=1..16),r[1]=ry[1],r[2]=ry[2]}:
<a name="line_230"></a>
<a name="line_231"></a><span style="color:red">#@ t_reduce 
</span><a name="line_232"></a>t_reduce := (a) -> FNF_y0(factor(subs(root_rule,expand(rationalize(simplify(a))))));
<a name="line_233"></a>
<a name="line_234"></a><span style="color:red">#@ t_xyz_reduce 
</span><a name="line_235"></a>t_xyz_reduce := (a) -> t_reduce(subs(t_to_xyz,a));
<a name="line_236"></a>
<a name="line_237"></a># SNB is a basis for KT over R(s[7],s[8]).  
<a name="line_238"></a># The function VNB converts its argument to the list of coefficients with respect to the basis SNB
<a name="line_239"></a>
<a name="line_240"></a><span style="color:red">#@ SNB 
</span><a name="line_241"></a>SNB := [seq(seq(seq(seq(seq(s[1]^i*s[2]^j*s[3]^k*t[1]^l*t[2]^m,m=0..1),l=0..1),k=0..1),j=0..1),i=0..1)];
<a name="line_242"></a>
<a name="line_243"></a><span style="color:red">#@ VNB 
</span><a name="line_244"></a>VNB := (u) -> [seq(seq(seq(seq(seq(
<a name="line_245"></a>               coeff(coeff(coeff(coeff(coeff(u,
<a name="line_246"></a>               s[1],i),s[2],j),s[3],k),t[1],l),t[2],m),
<a name="line_247"></a>               m=0..1),l=0..1),k=0..1),j=0..1),i=0..1)];
<a name="line_248"></a>
<a name="line_249"></a># The following relations can be used to express things in terms of SNB
<a name="line_250"></a>
<a name="line_251"></a><span style="color:red">#@ sn_rels
</span><a name="line_252"></a>
<a name="line_253"></a>sn_rels[1] := s[1]^2 - ((2*(3*s[7]*s[8]+2*s[7]-2*s[8]-3))/(s[7]*s[8]+2*s[7]-2*s[8]-1))*s[1] + 1:
<a name="line_254"></a>sn_rels[2] := s[2]^2 - ((2*(3*s[7]*s[8]-2*s[7]+2*s[8]-3))/(s[7]*s[8]-2*s[7]+2*s[8]-1))*s[2] + 1:
<a name="line_255"></a>sn_rels[3] := s[3]^2 - 2*s[7]*s[3] + 1:
<a name="line_256"></a>sn_rels[4] := s[4] - ((1/8)*(s[1]*s[2]*s[3]*s[7]^2*s[8]^2-s[1]*s[2]*s[7]^3*s[8]^2-3*s[1]*s[3]*s[7]^2*s[8]^2+3*s[1]*s[7]^3*s[8]^2-3*s[2]*s[3]*s[7]^2*s[8]^2+3*s[2]*s[7]^3*s[8]^2-4*s[1]*s[2]*s[3]*s[7]^2+6*s[1]*s[2]*s[3]*s[7]*s[8]-4*s[1]*s[2]*s[3]*s[8]^2+4*s[1]*s[2]*s[7]^3-6*s[1]*s[2]*s[7]^2*s[8]+4*s[1]*s[2]*s[7]*s[8]^2-4*s[1]*s[3]*s[7]^2*s[8]+4*s[1]*s[3]*s[7]*s[8]^2+4*s[1]*s[7]^3*s[8]-4*s[1]*s[7]^2*s[8]^2+4*s[2]*s[3]*s[7]^2*s[8]-4*s[2]*s[3]*s[7]*s[8]^2-4*s[2]*s[7]^3*s[8]+4*s[2]*s[7]^2*s[8]^2+9*s[3]*s[7]^2*s[8]^2-s[7]^3*s[8]^2+4*s[1]*s[3]*s[7]^2-2*s[1]*s[3]*s[7]*s[8]+4*s[1]*s[3]*s[8]^2-4*s[1]*s[7]^3+2*s[1]*s[7]^2*s[8]-4*s[1]*s[7]*s[8]^2+4*s[2]*s[3]*s[7]^2-2*s[2]*s[3]*s[7]*s[8]+4*s[2]*s[3]*s[8]^2-4*s[2]*s[7]^3+2*s[2]*s[7]^2*s[8]-4*s[2]*s[7]*s[8]^2+s[1]*s[2]*s[3]-s[1]*s[2]*s[7]+4*s[1]*s[3]*s[7]-4*s[1]*s[3]*s[8]-4*s[1]*s[7]^2+4*s[1]*s[7]*s[8]-4*s[2]*s[3]*s[7]+4*s[2]*s[3]*s[8]+4*s[2]*s[7]^2-4*s[2]*s[7]*s[8]-4*s[3]*s[7]^2-10*s[3]*s[7]*s[8]-4*s[3]*s[8]^2+4*s[7]^3+2*s[7]^2*s[8]-4*s[7]*s[8]^2-3*s[1]*s[3]+3*s[1]*s[7]-3*s[2]*s[3]+3*s[2]*s[7]+9*s[3]-9*s[7]+8*s[8])/((s[7]-1)*(s[7]+1)*(s[7]*s[8]-1))):
<a name="line_257"></a>sn_rels[5] := t[1]^2 - s[1]*(2*s[7] - s[3]):
<a name="line_258"></a>sn_rels[6] := t[2]^2-((1/8)*(-3*s[1]*s[2]*s[3]*s[7]^2*s[8]^2+3*s[1]*s[2]*s[7]^3*s[8]^2-4*s[1]*s[2]*s[3]*s[7]^2*s[8]+4*s[1]*s[2]*s[3]*s[7]*s[8]^2+4*s[1]*s[2]*s[7]^3*s[8]-4*s[1]*s[2]*s[7]^2*s[8]^2+s[1]*s[3]*s[7]^2*s[8]^2-s[1]*s[7]^3*s[8]^2+9*s[2]*s[3]*s[7]^2*s[8]^2-s[2]*s[7]^3*s[8]^2+4*s[1]*s[2]*s[3]*s[7]^2-2*s[1]*s[2]*s[3]*s[7]*s[8]+4*s[1]*s[2]*s[3]*s[8]^2-4*s[1]*s[2]*s[7]^3+2*s[1]*s[2]*s[7]^2*s[8]-4*s[1]*s[2]*s[7]*s[8]^2-3*s[3]*s[7]^2*s[8]^2+3*s[7]^3*s[8]^2+4*s[1]*s[2]*s[3]*s[7]-4*s[1]*s[2]*s[3]*s[8]-4*s[1]*s[2]*s[7]^2+4*s[1]*s[2]*s[7]*s[8]-4*s[1]*s[3]*s[7]^2+6*s[1]*s[3]*s[7]*s[8]-4*s[1]*s[3]*s[8]^2+4*s[1]*s[7]^3-6*s[1]*s[7]^2*s[8]+4*s[1]*s[7]*s[8]^2-4*s[2]*s[3]*s[7]^2-10*s[2]*s[3]*s[7]*s[8]-4*s[2]*s[3]*s[8]^2+4*s[2]*s[7]^3+2*s[2]*s[7]^2*s[8]-4*s[2]*s[7]*s[8]^2+4*s[3]*s[7]^2*s[8]-4*s[3]*s[7]*s[8]^2-4*s[7]^3*s[8]+4*s[7]^2*s[8]^2-3*s[1]*s[2]*s[3]+3*s[1]*s[2]*s[7]+4*s[3]*s[7]^2-2*s[3]*s[7]*s[8]+4*s[3]*s[8]^2-4*s[7]^3+2*s[7]^2*s[8]-4*s[7]*s[8]^2+s[1]*s[3]-s[1]*s[7]+9*s[2]*s[3]-9*s[2]*s[7]+8*s[2]*s[8]-4*s[3]*s[7]+4*s[3]*s[8]+4*s[7]^2-4*s[7]*s[8]-3*s[3]+3*s[7])/((s[7]-1)*(s[7]+1)*(s[7]*s[8]-1))):
<a name="line_259"></a>sn_rels[7] := t[3] - t[1]*s[3]:
<a name="line_260"></a>sn_rels[8] := t[4] - ((1/8)*t[2]*(s[1]*s[2]*s[3]*s[7]^2*s[8]^2-s[1]*s[2]*s[7]^3*s[8]^2-3*s[1]*s[3]*s[7]^2*s[8]^2+3*s[1]*s[7]^3*s[8]^2-3*s[2]*s[3]*s[7]^2*s[8]^2+3*s[2]*s[7]^3*s[8]^2-4*s[1]*s[2]*s[3]*s[7]^2+6*s[1]*s[2]*s[3]*s[7]*s[8]-4*s[1]*s[2]*s[3]*s[8]^2+4*s[1]*s[2]*s[7]^3-6*s[1]*s[2]*s[7]^2*s[8]+4*s[1]*s[2]*s[7]*s[8]^2-4*s[1]*s[3]*s[7]^2*s[8]+4*s[1]*s[3]*s[7]*s[8]^2+4*s[1]*s[7]^3*s[8]-4*s[1]*s[7]^2*s[8]^2+4*s[2]*s[3]*s[7]^2*s[8]-4*s[2]*s[3]*s[7]*s[8]^2-4*s[2]*s[7]^3*s[8]+4*s[2]*s[7]^2*s[8]^2+9*s[3]*s[7]^2*s[8]^2-s[7]^3*s[8]^2+4*s[1]*s[3]*s[7]^2-2*s[1]*s[3]*s[7]*s[8]+4*s[1]*s[3]*s[8]^2-4*s[1]*s[7]^3+2*s[1]*s[7]^2*s[8]-4*s[1]*s[7]*s[8]^2+4*s[2]*s[3]*s[7]^2-2*s[2]*s[3]*s[7]*s[8]+4*s[2]*s[3]*s[8]^2-4*s[2]*s[7]^3+2*s[2]*s[7]^2*s[8]-4*s[2]*s[7]*s[8]^2+s[1]*s[2]*s[3]-s[1]*s[2]*s[7]+4*s[1]*s[3]*s[7]-4*s[1]*s[3]*s[8]-4*s[1]*s[7]^2+4*s[1]*s[7]*s[8]-4*s[2]*s[3]*s[7]+4*s[2]*s[3]*s[8]+4*s[2]*s[7]^2-4*s[2]*s[7]*s[8]-4*s[3]*s[7]^2-10*s[3]*s[7]*s[8]-4*s[3]*s[8]^2+4*s[7]^3+2*s[7]^2*s[8]-4*s[7]*s[8]^2-3*s[1]*s[3]+3*s[1]*s[7]-3*s[2]*s[3]+3*s[2]*s[7]+9*s[3]-9*s[7]+8*s[8])/((s[7]-1)*(s[7]+1)*(s[7]*s[8]-1))):
<a name="line_261"></a>
<a name="line_262"></a># This is a basis for KT over R(z[1],z[2])
<a name="line_263"></a><span style="color:red">#@ BXYR 
</span><a name="line_264"></a>BXYR := [seq(seq(seq(seq(seq(seq(
<a name="line_265"></a>         x[1]^i*x[2]^j*y[1]^k*y[2]^l*r[1]^m*r[2]^n,
<a name="line_266"></a>         i=0..1),j=0..1),k=0..1),l=0..1),m=0..1),n=0..1)];
<a name="line_267"></a>
<a name="line_268"></a># The action of G[64] on KT preserves the above basis up to sign, with orbits as follows.
<a name="line_269"></a># These are enumerated so that the first 16 orbits have size one, and the actions on these
<a name="line_270"></a># orbits give the 16 one-dimensional characters of G[64].  The remaining 24 orbits all have 
<a name="line_271"></a># size two, and so give two-dimensional characters of G[64].  These are all irreducible, and
<a name="line_272"></a># each character occurs twice.  Orbits with the same character are adjacent in the list.
<a name="line_273"></a>
<a name="line_274"></a><span style="color:red">#@ BXYR_orbits 
</span><a name="line_275"></a>BXYR_orbits := [
<a name="line_276"></a> seq(seq(seq(seq([y[2]^i*y[1]^j*(x[1]*x[2])^k*(r[1]*r[2])^l],i=0..1),j=0..1),k=0..1),l=0..1),
<a name="line_277"></a> seq(seq(seq(y[2]^i*y[1]^j*(r[1]*r[2])^l*~[x[1],x[2]],i=0..1),j=0..1),l=0..1),
<a name="line_278"></a> seq(seq(seq(y[2]^i*y[1]^j*(x[1]*x[2])^l*~[r[1],r[2]],i=0..1),j=0..1),l=0..1),
<a name="line_279"></a> seq(seq(y[2]^i*y[1]^j*~[r[1]*x[1],r[2]*x[2]],i=0..1),j=0..1),
<a name="line_280"></a> seq(seq(y[2]^i*y[1]^j*~[r[1]*x[2],r[2]*x[1]],i=0..1),j=0..1)
<a name="line_281"></a>];
<a name="line_282"></a>
<a name="line_283"></a># Characters of G64
<a name="line_284"></a><span style="color:red">#@ orb_char 
</span><a name="line_285"></a>orb_char := proc(o)
<a name="line_286"></a> local c,T,eqs1,eqs2,sol1,sol2,p,q;
<a name="line_287"></a> if nops(o) = 1 then
<a name="line_288"></a>  return map(T -> factor(act_AT[T](o[1])/o[1]),G64);
<a name="line_289"></a> fi;
<a name="line_290"></a>
<a name="line_291"></a> c := [];
<a name="line_292"></a> for T in G64 do 
<a name="line_293"></a>  eqs1 := {coeffs(act_AT[T](o[1]) - p * o[1] - q*o[2],{x[1],x[2],y[1],y[2],r[1],r[2]})};
<a name="line_294"></a>  eqs2 := {coeffs(act_AT[T](o[2]) - p * o[1] - q*o[2],{x[1],x[2],y[1],y[2],r[1],r[2]})};
<a name="line_295"></a>  sol1 := solve(eqs1,{p,q});
<a name="line_296"></a>  sol2 := solve(eqs2,{p,q});
<a name="line_297"></a>  c := [op(c),subs(sol1,p) + subs(sol2,q)];
<a name="line_298"></a> od;
<a name="line_299"></a>
<a name="line_300"></a> return c;
<a name="line_301"></a>end:
<a name="line_302"></a>
<a name="line_303"></a><span style="color:red">#@ BXYR_chars 
</span><a name="line_304"></a>BXYR_chars := map(orb_char,BXYR_orbits):
<a name="line_305"></a>
<a name="line_306"></a><span style="color:red">#@ G64_chars 
</span><a name="line_307"></a>G64_chars := [
<a name="line_308"></a> seq(BXYR_chars[i],i=1..16),
<a name="line_309"></a> seq(BXYR_chars[16+2*i],i=1..12)
<a name="line_310"></a>];
<a name="line_311"></a>
<a name="line_312"></a><span style="color:red">#@ iso_AT 
</span><a name="line_313"></a>iso_AT := (a,i) -> add(act_AT[G64[j]](a) * G64_chars[i][j] * G64_chars[i][1]/64,j = 1..64);
<a name="line_314"></a>
<a name="line_315"></a>galois_check_zero := proc(a,n_)
<a name="line_316"></a> local n,x0,y0,z0,t0,s0,r0,u0;
<a name="line_317"></a> n := `if`(nargs > 1, n_, 26);
<a name="line_318"></a> x0 := inner_quasirational_points[n];
<a name="line_319"></a> y0 := combine(simplify(y_proj0(x0)));
<a name="line_320"></a> z0 := y0 ^~ 2;
<a name="line_321"></a> t0 := combine(simplify(expand(E_to_TTP(x0))));
<a name="line_322"></a> s0 := combine(simplify(expand(rationalize(eval(subs(t = t0,[seq(st[i],i=1..16)]))))));
<a name="line_323"></a> u0 := combine(simplify(expand(rationalize(eval(subs(t = t0,[seq(ut[i],i=1..16)]))))));
<a name="line_324"></a> r0[1] := combine(simplify(expand(sqrt(1 - y0[2]/sqrt(2)))));
<a name="line_325"></a> r0[2] := combine(simplify(expand(sqrt(1 + y0[2]/sqrt(2)))));
<a name="line_326"></a> return evalb(combine(simplify(eval(subs({x=x0,y=y0,z=z0,t=t0,s=s0,r=r0,u=u0},a)))) = 0);
<a name="line_327"></a>end:
<a name="line_328"></a>
<a name="line_329"></a>
<a name="line_330"></a>
  </pre>
 </body>
</html>
    