<html>
 <head>
 </head>
 <body>
  <pre>
    <a name="line_1"></a>`Class/Declare`(
<a name="line_2"></a> "KR_subfield",
<a name="line_3"></a> "An instance of this class represents a subfield of the field $KR$ of functions on $EX^*$ generated by the functions $x_i$ and $r_i$",
<a name="line_4"></a>
<a name="line_5"></a> ["Field","stabiliser"::list,"The list of elements of the group $G_{64}$ that act as the identity on this subfield"],
<a name="line_6"></a> ["Field","generating_sets"::list,"A list of generating sets for the subfield"],
<a name="line_7"></a> ["Field","conversion_rules"::table,"In the $(i,j)$ slot this should have a list of equations expressing the elements of generating set $i$ in terms of generating set $j$.  The $(i,i)$ slots can be left unset."],
<a name="line_8"></a>
<a name="line_9"></a> ["Method","check_stabiliser","",
<a name="line_10"></a>  proc(this)
<a name="line_11"></a>   local A,B,F,a,T,err,H;
<a name="line_12"></a>
<a name="line_13"></a>   A := {op(map(op,this["generating_sets"]))};
<a name="line_14"></a>   F := table():
<a name="line_15"></a>
<a name="line_16"></a>   for a in A do
<a name="line_17"></a>    for T in G64 do
<a name="line_18"></a>     err := simplify(act_AT[T](a) - a);
<a name="line_19"></a>     F[a,T] := evalb(err = 0);
<a name="line_20"></a>    od;
<a name="line_21"></a>   od;
<a name="line_22"></a>
<a name="line_23"></a>   for a in A do
<a name="line_24"></a>    for T in this["stabiliser"] do 
<a name="line_25"></a>     if not(F[a,T]) then
<a name="line_26"></a>      printf("%A is not fixed by %A\n",a,T);
<a name="line_27"></a>      return false;
<a name="line_28"></a>     fi;
<a name="line_29"></a>    od;
<a name="line_30"></a>   od;
<a name="line_31"></a>
<a name="line_32"></a>   for B in this["generating_sets"] do
<a name="line_33"></a>    H := sort(select(T -> (map(a -> F[a,T],{op(B)}) = {true}),G64));
<a name="line_34"></a>    if H <> this["stabiliser"] then
<a name="line_35"></a>     printf("stabiliser(%A) = %A\n",B,H);
<a name="line_36"></a>     return false;
<a name="line_37"></a>    fi;
<a name="line_38"></a>   od:
<a name="line_39"></a>
<a name="line_40"></a>   return true;
<a name="line_41"></a>  end
<a name="line_42"></a> ],
<a name="line_43"></a>
<a name="line_44"></a> ["Method","check_conversion","",
<a name="line_45"></a>  proc(this)
<a name="line_46"></a>   local i,j,n,A,B,C,R,E,e,err;
<a name="line_47"></a>
<a name="line_48"></a>   A := this["generating_sets"];
<a name="line_49"></a>   n := nops(A);
<a name="line_50"></a>   R := eval(this["conversion_rules"]);
<a name="line_51"></a>   for i from 1 to n do
<a name="line_52"></a>    for j from 1 to n do
<a name="line_53"></a>     if i <> j then
<a name="line_54"></a>      B := A[i]; 
<a name="line_55"></a>      C := A[j];
<a name="line_56"></a>      E := R[i,j];
<a name="line_57"></a>      if not(type(E,list(equation))) then
<a name="line_58"></a>       printf("rule (%d,%d) is not a list of equations \n",i,j);
<a name="line_59"></a>       return false;
<a name="line_60"></a>      fi;
<a name="line_61"></a>      if {op(map(lhs,E))} <> {op(B)} then
<a name="line_62"></a>       printf("rule (%d,%d) is not a list of equations for generating set %d\n",i,j,i);
<a name="line_63"></a>       return false;
<a name="line_64"></a>      fi;
<a name="line_65"></a>      if indets({op(map(rhs,E))}) minus {op(C)} <> {} then
<a name="line_66"></a>       printf("rule (%d,%d) does not express generating set %d in terms of generating set %d\n",i,j,i,j);
<a name="line_67"></a>       return false;
<a name="line_68"></a>      fi;
<a name="line_69"></a>
<a name="line_70"></a>      for e in E do 
<a name="line_71"></a>       if not(galois_check_zero(lhs(e) - rhs(e))) then
<a name="line_72"></a>        printf("in rule (%d,%d), equation %A is incorrect\n",i,j,e);
<a name="line_73"></a>        return false;
<a name="line_74"></a>       fi;
<a name="line_75"></a>      od;
<a name="line_76"></a>     fi;
<a name="line_77"></a>    od;
<a name="line_78"></a>   od;
<a name="line_79"></a>
<a name="line_80"></a>   return true;
<a name="line_81"></a>  end
<a name="line_82"></a> ],
<a name="line_83"></a>
<a name="line_84"></a> ["Method","check","",
<a name="line_85"></a>  proc(this)
<a name="line_86"></a>   this["check_stabiliser"] and this["check_conversion"];
<a name="line_87"></a>  end
<a name="line_88"></a> ]
<a name="line_89"></a>):
<a name="line_90"></a>
<a name="line_91"></a>KR_subfields := table():
<a name="line_92"></a>
<a name="line_93"></a>######################################################################
<a name="line_94"></a>
<a name="line_95"></a>KR_subfields[ 1] := `new/KR_subfield`():
<a name="line_96"></a>KR_subfields[ 1]["stabiliser"] := G64_subgroup_generated_by({LL,M,N,A1,A2});
<a name="line_97"></a>KR_subfields[ 1]["generating_sets"] := [[z[1],y[2]],[s[7],s[8]],[s[5],s[6],s[7],s[8]]];
<a name="line_98"></a>CR := table():
<a name="line_99"></a>CR[1,2] := [z[1] = zs[1],y[2] = ys[2]];
<a name="line_100"></a>CR[1,3] := [z[1] = zs[1],y[2] = ys[2]];
<a name="line_101"></a>CR[2,1] := subs(y[1] = sqrt(z[1]),[s[7] = sx[7],s[8] = sx[8]]);
<a name="line_102"></a>CR[2,3] := [s[7] = s[7], s[8] = s[8]];
<a name="line_103"></a>CR[3,1] := subs(y[1] = sqrt(z[1]),[s[5] = sx[5], s[6] = sx[6], s[7] = sx[7],s[8] = sx[8]]);
<a name="line_104"></a>CR[3,2] := [op(solve(s_rels[2],{s[5]})),op(solve(s_rels[3],{s[6]})),s[7] = s[7],s[8] = s[8]];
<a name="line_105"></a>KR_subfields[1]["conversion_rules"] := eval(CR):
<a name="line_106"></a>
<a name="line_107"></a>######################################################################
<a name="line_108"></a>
<a name="line_109"></a>KR_subfields[ 2] := `new/KR_subfield`():
<a name="line_110"></a>KR_subfields[ 2]["stabiliser"] := G64_subgroup_generated_by({LL,M,N,A1});
<a name="line_111"></a>KR_subfields[ 2]["generating_sets"] := [[z[1],y[2],r[2]],[s[2],s[7]],[s[2],s[8]],[s[2],s[5],s[6],s[7],s[8]]];
<a name="line_112"></a>
<a name="line_113"></a>CR := table():
<a name="line_114"></a>CR[1,4] := [z[1] = zs[1],y[2] = ys[2],r[2] = rs[2]];
<a name="line_115"></a>CR[1,2] := factor(subs(s[5] = 1/(s[2]/2 + 1/s[2]/2 - 2),subs(solve(s_rels[2],{s[8]}),CR[1,4])));
<a name="line_116"></a>CR[1,3] := factor(subs(s[5] = 1/(s[2]/2 + 1/s[2]/2 - 2),subs(solve(s_rels[2],{s[7]}),CR[1,4])));
<a name="line_117"></a>CR[2,1] := subs(y[1] = sqrt(z[1]),[s[2] = sx[2],s[7] = sx[7]]);
<a name="line_118"></a>CR[2,3] := [s[2] = s[2],s[7] = factor(subs(s[5] = 1/(s[2]/2 + 1/s[2]/2 - 2),solve(s_rels[2],s[7])))];
<a name="line_119"></a>CR[2,4] := [s[2] = s[2],s[7] = s[7]];
<a name="line_120"></a>CR[3,1] := subs(y[1] = sqrt(z[1]),[s[2] = sx[2],s[8] = sx[8]]);
<a name="line_121"></a>CR[3,2] := [s[2] = s[2],s[8] = factor(subs(s[5] = 1/(s[2]/2 + 1/s[2]/2 - 2),solve(s_rels[2],s[8])))];
<a name="line_122"></a>CR[3,4] := [s[2] = s[2],s[8] = s[8]];
<a name="line_123"></a>CR[4,1] := subs(y[1] = sqrt(z[1]),[seq(s[i] = sx[i],i in [2,5,6,7,8])]);
<a name="line_124"></a>CR[4,2] := [s[2] = s[2], s[5] = 1/(s[2]/2 + 1/s[2]/2 - 2), s[6] = (s[2]/2 + 1/s[2]/2 - 2), s[7] = s[7],
<a name="line_125"></a>            s[8] = factor(subs(s[5] = 1/(s[2]/2 + 1/s[2]/2 - 2),solve(s_rels[2],s[8])))];
<a name="line_126"></a>CR[4,3] := [s[2] = s[2], s[5] = 1/(s[2]/2 + 1/s[2]/2 - 2), s[6] = (s[2]/2 + 1/s[2]/2 - 2), s[8] = s[8],
<a name="line_127"></a>            s[7] = factor(subs(s[5] = 1/(s[2]/2 + 1/s[2]/2 - 2),solve(s_rels[2],s[7])))];
<a name="line_128"></a>KR_subfields[2]["conversion_rules"] := eval(CR):
<a name="line_129"></a>
<a name="line_130"></a>
<a name="line_131"></a>######################################################################
<a name="line_132"></a>
<a name="line_133"></a>KR_subfields[ 3] := `new/KR_subfield`():
<a name="line_134"></a>KR_subfields[ 3]["stabiliser"] := G64_subgroup_generated_by({LL,M,N,A2});
<a name="line_135"></a>KR_subfields[ 3]["generating_sets"] := [[z[1],y[2],r[1]],[s[1],s[7]],[s[1],s[8]],[s[1],s[5],s[6],s[7],s[8]]];
<a name="line_136"></a>
<a name="line_137"></a>CR := table():
<a name="line_138"></a>CR[1,4] := [z[1] = zs[1],y[2] = ys[2],r[1] = rs[1]];
<a name="line_139"></a>CR[1,2] := factor(subs(s[5] = (s[1]/2 + 1/s[1]/2 - 2),subs(solve(s_rels[2],{s[8]}),CR[1,4])));
<a name="line_140"></a>CR[1,3] := factor(subs(s[5] = (s[1]/2 + 1/s[1]/2 - 2),subs(solve(s_rels[2],{s[7]}),CR[1,4])));
<a name="line_141"></a>CR[2,1] := subs(y[1] = sqrt(z[1]),[s[1] = sx[1],s[7] = sx[7]]);
<a name="line_142"></a>CR[2,3] := [s[1] = s[1],s[7] = factor(subs(s[5] = (s[1]/2 + 1/s[1]/2 - 2),solve(s_rels[2],s[7])))];
<a name="line_143"></a>CR[2,4] := [s[1] = s[1],s[7] = s[7]];
<a name="line_144"></a>CR[3,1] := subs(y[1] = sqrt(z[1]),[s[1] = sx[1],s[8] = sx[8]]);
<a name="line_145"></a>CR[3,2] := [s[1] = s[1],s[8] = factor(subs(s[5] = (s[1]/2 + 1/s[1]/2 - 2),solve(s_rels[2],s[8])))];
<a name="line_146"></a>CR[3,4] := [s[1] = s[1],s[8] = s[8]];
<a name="line_147"></a>CR[4,1] := subs(y[1] = sqrt(z[1]),[seq(s[i] = sx[i],i in [1,5,6,7,8])]);
<a name="line_148"></a>CR[4,2] := [s[1] = s[1], s[5] = (s[1]/2 + 1/s[1]/2 - 2), s[6] = 1/(s[1]/2 + 1/s[1]/2 - 2), s[7] = s[7],
<a name="line_149"></a>            s[8] = factor(subs(s[5] = (s[1]/2 + 1/s[1]/2 - 2),solve(s_rels[2],s[8])))];
<a name="line_150"></a>CR[4,3] := [s[1] = s[1], s[5] = (s[1]/2 + 1/s[1]/2 - 2), s[6] = 1/(s[1]/2 + 1/s[1]/2 - 2), s[8] = s[8],
<a name="line_151"></a>            s[7] = factor(subs(s[5] = (s[1]/2 + 1/s[1]/2 - 2),solve(s_rels[2],s[7])))];
<a name="line_152"></a>KR_subfields[ 3]["conversion_rules"] := eval(CR):
<a name="line_153"></a>
<a name="line_154"></a>######################################################################
<a name="line_155"></a>
<a name="line_156"></a>KR_subfields[ 4] := `new/KR_subfield`():
<a name="line_157"></a>KR_subfields[ 4]["stabiliser"] := G64_subgroup_generated_by({LL,MA1,N,A2});
<a name="line_158"></a>KR_subfields[ 4]["generating_sets"] := [[s[3],s[5]],[s[3],s[6]],[s[3],s[5],s[6],s[7],s[8]]];
<a name="line_159"></a>CR := table():
<a name="line_160"></a>CR[1,2] := [s[3] = s[3],s[5] = 1/s[6]];
<a name="line_161"></a>CR[1,3] := [s[3] = s[3],s[5] = s[5]];
<a name="line_162"></a>CR[2,1] := [s[3] = s[3],s[6] = 1/s[5]];
<a name="line_163"></a>CR[2,3] := [s[3] = s[3],s[6] = s[6]];
<a name="line_164"></a>CR[3,1] := [s[3] = s[3],s[5] = s[5],s[6] = 1/s[5],s[7] = s[3]/2 + 1/s[3]/2,
<a name="line_165"></a>            s[8] = -(2*(s[3]^2*s[5]+s[3]^2-s[3]*s[5]+s[3]+s[5]+1))/(s[3]^2*s[5]-s[3]^2-4*s[3]*s[5]-4*s[3]+s[5]-1)];
<a name="line_166"></a>CR[3,2] := [s[3] = s[3],s[5] = 1/s[6],s[6] = s[6],s[7] = s[3]/2 + 1/s[3]/2,
<a name="line_167"></a>            s[8] =  (2*(s[3]^2*s[6]+s[3]^2+s[3]*s[6]-s[3]+s[6]+1))/(s[3]^2*s[6]-s[3]^2+4*s[3]*s[6]+4*s[3]+s[6]-1)];
<a name="line_168"></a>KR_subfields[ 4]["conversion_rules"] := eval(CR):
<a name="line_169"></a>
<a name="line_170"></a>######################################################################
<a name="line_171"></a>
<a name="line_172"></a>KR_subfields[ 5] := `new/KR_subfield`():
<a name="line_173"></a>KR_subfields[ 5]["stabiliser"] := G64_subgroup_generated_by({LL,MA2,N,A1});
<a name="line_174"></a>KR_subfields[ 5]["generating_sets"] := [[s[4],s[5]],[s[4],s[6]],[s[4],s[5],s[6],s[7],s[8]]];
<a name="line_175"></a>CR := table():
<a name="line_176"></a>CR[1,2] := [s[4] = s[4],s[5] = 1/s[6]];
<a name="line_177"></a>CR[1,3] := [s[4] = s[4],s[5] = s[5]];
<a name="line_178"></a>CR[2,1] := [s[4] = s[4],s[6] = 1/s[5]];
<a name="line_179"></a>CR[2,3] := [s[4] = s[4],s[6] = s[6]];
<a name="line_180"></a>CR[3,1] := [s[4] = s[4],s[5] = s[5],s[6] = 1/s[5],s[8] = s[4]/2 + 1/s[4]/2,
<a name="line_181"></a>            s[7] =  (2*(s[4]^2*s[5]+s[4]^2+s[4]*s[5]-s[4]+s[5]+1))/(s[4]^2*s[5]-s[4]^2+4*s[4]*s[5]+4*s[4]+s[5]-1)];
<a name="line_182"></a>CR[3,2] := [s[4] = s[4],s[5] = 1/s[6],s[6] = s[6],s[8] = s[4]/2 + 1/s[4]/2,
<a name="line_183"></a>            s[7] = -(2*(s[4]^2*s[6]+s[4]^2-s[4]*s[6]+s[4]+s[6]+1))/(s[4]^2*s[6]-s[4]^2-4*s[4]*s[6]-4*s[4]+s[6]-1)];
<a name="line_184"></a>KR_subfields[ 5]["conversion_rules"] := eval(CR):
<a name="line_185"></a>KR_subfields[ 5]["check_stabiliser"];
<a name="line_186"></a>KR_subfields[ 5]["check_conversion"];
<a name="line_187"></a>
<a name="line_188"></a>######################################################################
<a name="line_189"></a>
<a name="line_190"></a>KR_subfields[ 6] := `new/KR_subfield`():
<a name="line_191"></a>KR_subfields[ 6]["stabiliser"] := G64_subgroup_generated_by({LL,N,A2});
<a name="line_192"></a>KR_subfields[ 6]["generating_sets"] := [[y[1],r[1]],[y[1],y[2],r[1]],[s[1],s[3]],[s[1],s[3],s[5],s[6],s[7],s[8]]];
<a name="line_193"></a>
<a name="line_194"></a>CR := table():
<a name="line_195"></a>CR[1,2] := [y[1] = y[1],r[1] = r[1]];
<a name="line_196"></a>CR[1,3] := [y[1] = ys[1],r[1] = rs[1]];
<a name="line_197"></a>CR[1,4] := [y[1] = ys[1],r[1] = rs[1]];
<a name="line_198"></a>CR[2,1] := [y[1] = y[1],y[2] = y2r[1],r[1] = r[1]];
<a name="line_199"></a>CR[2,3] := [y[1] = ys[1],y[2] = (sqrt(2) - (s[1]+1)^2/(s[1]-1)^2/sqrt(2)),r[1] = rs[1]];
<a name="line_200"></a>CR[2,4] := [y[1] = ys[1],y[2] = ys[2],r[1] = rs[1]];
<a name="line_201"></a>CR[3,1] := [s[1] = sx[1],s[3] = sx[3]];
<a name="line_202"></a>CR[3,2] := [s[1] = sx[1],s[3] = sx[3]];
<a name="line_203"></a>CR[3,4] := [s[1] = s[1],s[3] = s[3]];
<a name="line_204"></a>CR[4,1] := subs(y[2] = y2r[1],[seq(s[i] = sx[i],i in [1,3,5,6,7,8])]);
<a name="line_205"></a>CR[4,2] := [seq(s[i] = sx[i],i in [1,3,5,6,7,8])];
<a name="line_206"></a>CR[4,3] := [s[1] = s[1], s[3] = s[3],
<a name="line_207"></a>            s[5] = (s[1]/2 + 1/s[1]/2 - 2), s[6] = 1/(s[1]/2 + 1/s[1]/2 - 2),
<a name="line_208"></a>            s[7] = s[3]/2 + 1/s[3]/2, 
<a name="line_209"></a>            s[8] = -(2*(s[1]^2*s[3]^2-s[1]^2*s[3]-2*s[1]*s[3]^2+s[1]^2+6*s[1]*s[3]+s[3]^2-2*s[1]-s[3]+1))/
<a name="line_210"></a>                     (s[1]^2*s[3]^2-4*s[1]^2*s[3]-6*s[1]*s[3]^2+s[1]^2+8*s[1]*s[3]+s[3]^2-6*s[1]-4*s[3]+1)
<a name="line_211"></a>           ];
<a name="line_212"></a>KR_subfields[ 6]["conversion_rules"] := eval(CR):
<a name="line_213"></a>
<a name="line_214"></a>######################################################################
<a name="line_215"></a>
<a name="line_216"></a>KR_subfields[ 7] := `new/KR_subfield`():
<a name="line_217"></a>KR_subfields[ 7]["stabiliser"] := G64_subgroup_generated_by({LL,N,A1});
<a name="line_218"></a>KR_subfields[ 7]["generating_sets"] := [[y[1],r[2]],[y[1],y[2],r[2]],[s[2],s[4]],[s[2],s[4],s[5],s[6],s[7],s[8]]];
<a name="line_219"></a>
<a name="line_220"></a>CR := table():
<a name="line_221"></a>CR[1,2] := [y[1] = y[1],r[2] = r[2]];
<a name="line_222"></a>CR[1,3] := [y[1] = act_AT[L](ys[1]),r[2] = rs[2]];
<a name="line_223"></a>CR[1,4] := [y[1] = act_AT[L](ys[1]),r[2] = rs[2]];
<a name="line_224"></a>CR[2,1] := [y[1] = y[1],y[2] = y2r[2],r[2] = r[2]];
<a name="line_225"></a>CR[2,3] := [y[1] = act_AT[L](ys[1]),y[2] = -(sqrt(2) - (s[2]+1)^2/(s[2]-1)^2/sqrt(2)),r[2] = rs[2]];
<a name="line_226"></a>CR[2,4] := [y[1] = act_AT[L](ys[1]),y[2] = ys[2],r[2] = rs[2]];
<a name="line_227"></a>CR[3,1] := [s[2] = sx[2],s[4] = sx[4]];
<a name="line_228"></a>CR[3,2] := [s[2] = sx[2],s[4] = sx[4]];
<a name="line_229"></a>CR[3,4] := [s[2] =  s[2],s[4] =  s[4]];
<a name="line_230"></a>CR[4,1] := subs(y[2] = y2r[2],[seq(s[i] = sx[i],i in [2,4,5,6,7,8])]);
<a name="line_231"></a>CR[4,2] := [seq(s[i] = sx[i],i in [2,4,5,6,7,8])];
<a name="line_232"></a>CR[4,3] := [s[2] = s[2], s[4] = s[4],
<a name="line_233"></a>            s[5] = 1/(s[2]/2 + 1/s[2]/2 - 2), s[6] = (s[2]/2 + 1/s[2]/2 - 2),
<a name="line_234"></a>            s[8] = s[4]/2 + 1/s[4]/2, 
<a name="line_235"></a>            s[7] = -(2*(s[2]^2*s[4]^2-s[2]^2*s[4]-2*s[2]*s[4]^2+s[2]^2+6*s[2]*s[4]+s[4]^2-2*s[2]-s[4]+1))/
<a name="line_236"></a>                     (s[2]^2*s[4]^2-4*s[2]^2*s[4]-6*s[2]*s[4]^2+s[2]^2+8*s[2]*s[4]+s[4]^2-6*s[2]-4*s[4]+1)
<a name="line_237"></a>           ];
<a name="line_238"></a>KR_subfields[ 7]["conversion_rules"] := eval(CR):
<a name="line_239"></a>
<a name="line_240"></a>######################################################################
<a name="line_241"></a>
<a name="line_242"></a>KR_subfields[ 8] := `new/KR_subfield`():
<a name="line_243"></a>KR_subfields[ 8]["stabiliser"] := G64_subgroup_generated_by({N,A2});
<a name="line_244"></a>KR_subfields[ 8]["generating_sets"] := [[y[1],x[1],r[1]],[y[1],y[2],x[1],r[1]],[t[1],t[3]],[t[1],t[3],s[1],s[3],s[5],s[6],s[7],s[8]]];
<a name="line_245"></a>
<a name="line_246"></a>CR := table():
<a name="line_247"></a>CR[1,2] := [y[1] = y[1],x[1] = x[1],r[1] = r[1]];
<a name="line_248"></a>CR[1,3] := [y[1] = yt[1],x[1] = xt[1],r[1] = rt[1]];
<a name="line_249"></a>CR[1,4] := [y[1] = yt[1],x[1] = xt[1],r[1] = rt[1]];
<a name="line_250"></a>CR[2,1] := [y[1] = y[1],y[2] = y2r[1],x[1] = x[1],r[1] = r[1]];
<a name="line_251"></a>CR[2,3] := [y[1] = yt[1],y[2] = (t[1]^2*t[3]^2-6*t[1]*t[3]+1)/(t[1]*t[3]-1)^2/sqrt(2),x[1] = xt[1],r[1] = rt[1]];
<a name="line_252"></a>CR[2,4] := [y[1] = yt[1],y[2] = (t[1]^2*t[3]^2-6*t[1]*t[3]+1)/(t[1]*t[3]-1)^2/sqrt(2),x[1] = xt[1],r[1] = rt[1]];
<a name="line_253"></a>CR[3,1] := [t[1] = tx[1],t[3] = tx[3]];
<a name="line_254"></a>CR[3,2] := [t[1] = tx[1],t[3] = tx[3]];
<a name="line_255"></a>CR[3,4] := [t[1] = t[1],t[3] = t[3]];
<a name="line_256"></a>CR[4,1] := [t[1] = tx[1],t[3] = tx[3],op(subs(y[2] = y2r[1],[seq(s[i] = sx[i],i in [1,3,5,6,7,8])]))];
<a name="line_257"></a>CR[4,2] := [t[1] = tx[1],t[3] = tx[3],seq(s[i] = sx[i],i in [1,3,5,6,7,8])];
<a name="line_258"></a>CR[4,3] := [t[1] = t[1],t[3] = t[3],s[1] = st[1],s[3] = st[3],s[5] = st[5],s[6] = 1/st[5],s[7] = st[7],
<a name="line_259"></a>            s[8] = -(2*(t[1]^4*t[3]^2-t[1]^3*t[3]^3+t[1]^2*t[3]^4-2*t[1]^3*t[3]+6*t[1]^2*t[3]^2-2*t[1]*t[3]^3+t[1]^2-t[1]*t[3]+t[3]^2))/
<a name="line_260"></a>                    (t[1]^4*t[3]^2-4*t[1]^3*t[3]^3+t[1]^2*t[3]^4-6*t[1]^3*t[3]+8*t[1]^2*t[3]^2-6*t[1]*t[3]^3+t[1]^2-4*t[1]*t[3]+t[3]^2)
<a name="line_261"></a>           ];
<a name="line_262"></a>KR_subfields[ 8]["conversion_rules"] := eval(CR):
<a name="line_263"></a>
<a name="line_264"></a>######################################################################
<a name="line_265"></a>
<a name="line_266"></a>KR_subfields[ 9] := `new/KR_subfield`():
<a name="line_267"></a>KR_subfields[ 9]["stabiliser"] := G64_subgroup_generated_by({LLN,A1});
<a name="line_268"></a>KR_subfields[ 9]["generating_sets"] := [[y[1],x[2],r[2]],[y[1],y[2],x[2],r[2]],[t[2],t[4]],[t[2],t[4],s[2],s[4],s[5],s[6],s[7],s[8]]];
<a name="line_269"></a>
<a name="line_270"></a>CR := table():
<a name="line_271"></a>CR[1,2] := [y[1] = y[1],x[2] = x[2],r[2] = r[2]];
<a name="line_272"></a>CR[1,3] := [y[1] = act_AT[L](yt[1]),x[2] = xt[2],r[2] = rt[2]];
<a name="line_273"></a>CR[1,4] := [y[1] = act_AT[L](yt[1]),x[2] = xt[2],r[2] = rt[2]];
<a name="line_274"></a>CR[2,1] := [y[1] = y[1],y[2] = y2r[2],x[2] = x[2],r[2] = r[2]];
<a name="line_275"></a>CR[2,3] := [y[1] = act_AT[L](yt[1]),y[2] = -(t[2]^2*t[4]^2-6*t[2]*t[4]+1)/(t[2]*t[4]-1)^2/sqrt(2),x[2] = xt[2],r[2] = rt[2]];
<a name="line_276"></a>CR[2,4] := [y[1] = act_AT[L](yt[1]),y[2] = -(t[2]^2*t[4]^2-6*t[2]*t[4]+1)/(t[2]*t[4]-1)^2/sqrt(2),x[2] = xt[2],r[2] = rt[2]];
<a name="line_277"></a>CR[3,1] := [t[2] = tx[2],t[4] = tx[4]];
<a name="line_278"></a>CR[3,2] := [t[2] = tx[2],t[4] = tx[4]];
<a name="line_279"></a>CR[3,4] := [t[2] = t[2],t[4] = t[4]];
<a name="line_280"></a>CR[4,1] := [t[2] = tx[2],t[4] = tx[4],op(subs(y[2] = y2r[2],[seq(s[i] = sx[i],i in [2,4,5,6,7,8])]))];
<a name="line_281"></a>CR[4,2] := [t[2] = tx[2],t[4] = tx[4],seq(s[i] = sx[i],i in [2,4,5,6,7,8])];
<a name="line_282"></a>CR[4,3] := [t[2] = t[2],t[4] = t[4],s[2] = st[2],s[4] = st[4],s[5] = 1/st[6],s[6] = st[6],s[8] = st[8],
<a name="line_283"></a>            s[7] = -(2*(t[2]^4*t[4]^2-t[2]^3*t[4]^3+t[2]^2*t[4]^4-2*t[2]^3*t[4]+6*t[2]^2*t[4]^2-2*t[2]*t[4]^3+t[2]^2-t[2]*t[4]+t[4]^2))/
<a name="line_284"></a>                    (t[2]^4*t[4]^2-4*t[2]^3*t[4]^3+t[2]^2*t[4]^4-6*t[2]^3*t[4]+8*t[2]^2*t[4]^2-6*t[2]*t[4]^3+t[2]^2-4*t[2]*t[4]+t[4]^2)
<a name="line_285"></a>           ];
<a name="line_286"></a>KR_subfields[ 9]["conversion_rules"] := eval(CR):
<a name="line_287"></a>
<a name="line_288"></a>######################################################################
<a name="line_289"></a>
<a name="line_290"></a>KR_subfields[10] := `new/KR_subfield`():
<a name="line_291"></a>KR_subfields[10]["stabiliser"] := G64_subgroup_generated_by({LL,M,N});
<a name="line_292"></a>KR_subfields[10]["generating_sets"] := [[z[1],y[2],r[1],r[2]],[s[1],s[2],s[7]],[s[1],s[2],s[8]],[s[1],s[2],s[5],s[6],s[7],s[8]]];
<a name="line_293"></a>
<a name="line_294"></a>CR := table():
<a name="line_295"></a>CR[1,2] := [z[1] = 2*(s[1]-1)^2/(s[1]+1)^2*(s[7]-1)/(s[7]+1),y[2] = (s[1]^2-6*s[1]+1)/(s[1]-1)^2/sqrt(2),r[1] = rs[1],r[2] = rs[2]];
<a name="line_296"></a>CR[1,3] := [z[1] = 2*(s[2]-1)^2/(s[2]+1)^2*(s[8]-1)/(s[8]+1),y[2] = (s[1]^2-6*s[1]+1)/(s[1]-1)^2/sqrt(2),r[1] = rs[1],r[2] = rs[2]];
<a name="line_297"></a>CR[1,4] := [z[1] = zs[1],y[2] = ys[2],r[1] = rs[1],r[2] = rs[2]];
<a name="line_298"></a>CR[2,1] := subs(y[1] = sqrt(z[1]),[s[1] = sx[1],s[2] = sx[2],s[7] = sx[7]]);
<a name="line_299"></a>CR[2,3] := [s[1] = s[1],s[2] = s[2],s[7] = -(2*s[2]^2*s[8]-s[2]^2-4*s[2]*s[8]+6*s[2]+2*s[8]-1)/(s[2]^2*s[8]-2*s[2]^2-6*s[2]*s[8]+4*s[2]+s[8]-2)];
<a name="line_300"></a>CR[2,4] := [s[1] = s[1],s[2] = s[2],s[7] = s[7]];
<a name="line_301"></a>CR[3,1] := subs(y[1] = sqrt(z[1]),[s[1] = sx[1],s[2] = sx[2],s[8] = sx[8]]);
<a name="line_302"></a>CR[3,2] := [s[1] = s[1],s[2] = s[2],s[8] = -(2*s[1]^2*s[7]-s[1]^2-4*s[1]*s[7]+6*s[1]+2*s[7]-1)/(s[1]^2*s[7]-2*s[1]^2-6*s[1]*s[7]+4*s[1]+s[7]-2)];
<a name="line_303"></a>CR[3,4] := [s[1] = s[1],s[2] = s[2],s[8] = s[8]];
<a name="line_304"></a>CR[4,1] := subs(y[1] = sqrt(z[1]),[seq(s[i] = sx[i],i in [1,2,5,6,7,8])]);
<a name="line_305"></a>CR[4,2] := [s[1] = s[1],s[2] = s[2],s[5] = (s[1]/2 + 1/s[1]/2 - 2),s[6] = (s[2]/2 + 1/s[2]/2 - 2),s[7] = s[7],
<a name="line_306"></a>            s[8] = -(2*s[1]^2*s[7]-s[1]^2-4*s[1]*s[7]+6*s[1]+2*s[7]-1)/(s[1]^2*s[7]-2*s[1]^2-6*s[1]*s[7]+4*s[1]+s[7]-2)];
<a name="line_307"></a>CR[4,3] := [s[1] = s[1],s[2] = s[2],s[5] = (s[1]/2 + 1/s[1]/2 - 2),s[6] = (s[2]/2 + 1/s[2]/2 - 2),s[8] = s[8],
<a name="line_308"></a>            s[7] = -(2*s[2]^2*s[8]-s[2]^2-4*s[2]*s[8]+6*s[2]+2*s[8]-1)/(s[2]^2*s[8]-2*s[2]^2-6*s[2]*s[8]+4*s[2]+s[8]-2)];
<a name="line_309"></a>KR_subfields[10]["conversion_rules"] := eval(CR):
<a name="line_310"></a>
<a name="line_311"></a>######################################################################
<a name="line_312"></a>
<a name="line_313"></a>KR_subfields[11] := `new/KR_subfield`():
<a name="line_314"></a>KR_subfields[11]["stabiliser"] := G64_subgroup_generated_by({M,N});
<a name="line_315"></a>KR_subfields[11]["generating_sets"] := [[z[1],y[2],x[1],r[1],r[2]],[s[1],s[2],u[1]]];
<a name="line_316"></a>
<a name="line_317"></a>CR := table():
<a name="line_318"></a>CR[1,2] := [z[1] = 2*(1-s[1])^2/(1+s[1])^2*(1-4*s[1]/u[1]^2),
<a name="line_319"></a>            y[2] = (s[1]^2-6*s[1]+1)/(s[1]-1)^2/sqrt(2),
<a name="line_320"></a>            x[1] = sqrt(8)/(1-1/s[1])/u[1],
<a name="line_321"></a>            r[1] = rs[1],r[2] = rs[2]];
<a name="line_322"></a>CR[2,1] := [s[1]=sx[1],s[2]=sx[2],u[1] = -sqrt(8)*x[1]/(1-r[1]^2*z[1])/(1-sqrt(2)*r[1])];
<a name="line_323"></a>KR_subfields[11]["conversion_rules"] := eval(CR):
<a name="line_324"></a>
  </pre>
 </body>
</html>
    